### ISSUE TITLE
Bind to logout button?

### ISSUE THREAD

**Issue by pettrs** [Im2be/afk-countdown#1]
I put mine down there, but possibly have it as an option to just put the countdown on the logout icon by deafult?

![image](https://user-images.githubusercontent.com/75093127/167829458-837bfb15-0cff-40b1-9bc2-64f221426b1f.png)

**Comment by m0bilebtw** [comment]
I do the same and have been considering implementing this option when I get the time, @Im2be would you be open to this being added?

**Comment by m0bilebtw** [comment]
For anyone interested I do have a prototype of this working beautifully - still need to handle disabling the infobox when toggling on the render on logout button config and small things like that.

Automatically uses the same font used for infoboxes in RuneLite config.
Resizable classic and fixed show on the logout stone, resizable modern doesn't have that stone so it shows on the X (logout) button by the minimap instead.

Example screenshot:

![image](https://user-images.githubusercontent.com/62370532/175786446-ded09577-5269-4eee-9512-8eef1997c1c3.png)

**Comment by Im2be** [comment]
Well done. I pretty much don't play anymore so I'll assume you tested it and everything. I've already made a pull request to update the plugin-hub. Thanks for making the PR @m0bilebtw

**Comment by m0bilebtw** [comment]
Yep, it's all good to go! :) Thanks for the quick merge and update PR!
