### ISSUE TITLE
Add support for Logout Timer plugin

### ISSUE THREAD

**Issue by larsiny** [Im2be/afk-countdown#3]
The new Logout Timer plugin added in https://github.com/runelite/runelite/commit/b58e3817d5e1069552944e2c01be0030adc9f0c0#diff-36bf7e903386494fb31a78acb18418f61a47d19e17b152b00ec07ef0922d879f allows changing the idle timer to up to 25 mins.

**Comment by Im2be** [comment]
Fixed with v1.3 (once they close the pull request on the plugin hub)
